---
  - name: 1.1.1 Create Separate Partition for /tmp
    command: grep "[[:space:]]/tmp[[:space:]]" /etc/fstab

  - name: 1.1.2 Set nodev option for /tmp Partition
    shell: grep /tmp /etc/fstab | grep nodev
  
  - name: 1.1.3 Set nosuid option for /tmp Partition
    shell: grep /tmp /etc/fstab | grep nosuid

  - name: 1.1.4 Set noexec option for /tmp Partition
    shell: grep /tmp /etc/fstab | grep noexec

  - name: 1.1.5 Create Separate Partition for /var
    command: grep "[[:space:]]/var[[:space:]]" /etc/fstab

  - name: 1.1.6 Bind Mount the /var/tmp directory to /tmp
    shell: grep -e "^/tmp" /etc/fstab | grep /var/tmp

  - name: 1.1.7 Create Separate Partition for /var/log
    command: grep /var/log /etc/fstab

  - name: 1.1.8 Create Separate Partition for /var/log/audit
    command: grep /var/log/audit /etc/fstab

  - name: 1.1.9 Create Separate Partition for /home
    command: grep /home /etc/fstab

  - name: 1.1.10 Add nodev Option to /home
    shell: grep /home /etc/fstab | grep nodev
#    when: facter_role != 'dev'
  
  - name: 1.1.14 Add nodev Option to /dev/shm Partition
    shell: grep /dev/shm /etc/fstab | grep nodev

  - name: 1.1.15 Add nosuid Option to /dev/shm Partition
    shell: grep /dev/shm /etc/fstab | grep nosuid

  - name: 1.1.16 Add noexec Option to /dev/shm Partition
    shell: grep /dev/shm /etc/fstab | grep noexec

  - name: 1.1.17 Set Sticky Bit on All World-Writable Directories
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
