---

  - name: 5.2.1 Disable Source Routed Packet Acceptance
    command: grep "net.ipv4.conf.all.accept_source_route = 0" /etc/sysctl.conf

  - name: 5.2.2 Disable ICMP Redirect Acceptance
    command: grep "net.ipv4.conf.all.accept_redirects = 0" /etc/sysctl.conf

  - name: 5.2.3 Disable Secure ICMP Redirect Acceptance
    command: grep "net.ipv4.conf.all.secure_redirects = 0" /etc/sysctl.conf

  - name: 5.2.4 Log Suspicious Packets
    command: grep "net.ipv4.conf.all.log_martians = 1" /etc/sysctl.conf

  - name: 5.2.5 Enable Ignore Broadcast Requests
    command: grep "net.ipv4.icmp_echo_ignore_broadcasts = 1" /etc/sysctl.conf

  - name: 5.2.6 Enable Bad Error Message Protection
    command: grep "net.ipv4.icmp_ignore_bogus_error_responses = 1" /etc/sysctl.conf

  - name: 5.2.7 Enable RFC-recommended Source Route Validation
    command: grep "net.ipv4.conf.all.rp_filter = 1" /etc/sysctl.conf

  - name: 5.2.8 Enable TCP SYN Cookies
    command: grep "net.ipv4.tcp_syncookies = 1" /etc/sysctl.conf
