---
  - include: 1.1.yml tags=1.1
  - include: 1.2.yml tags=1.2
  - include: 1.3.yml tags=1.3
  - include: 1.4.yml tags=1.4
  - include: 1.5.yml tags=1.5
  - include: 1.6.yml tags=1.6
  - include: 1.7.yml tags=1.7
  - include: 2.1.yml tags=2.1
  - include: 3.yml tags=3
  - include: 4.1.yml tags=4.1
  - include: 4.2.yml tags=4.2
  - include: 4.3.yml tags=4.3
  - include: 5.1.yml tags=5.1
  - include: 5.2.yml tags=5.2
  - include: 5.3.yml tags=5.3
  - include: 5.4.yml tags=5.4
  - include: 5.5.yml tags=5.5
  - include: 5.6.yml tags=5.6
  - include: 5.7.yml tags=5.7
  - include: 5.8.yml tags=5.8
  - include: 6.1.yml tags=6.1
  - include: 6.2.yml tags=6.2
  - include: 6.3.yml tags=6.3
  - include: 6.4.yml tags=6.4
  - include: 6.5.yml tags=6.5
  - include: 7.1.yml tags=7.1
  - include: 7.2.yml tags=7.2
  - include: 7.3.yml tags=7.3
  - include: 7.4.yml tags=7.4
  - include: 7.5.yml tags=7.5
  - include: 8.1.yml tags=8.1
  - include: 8.2.yml tags=8.2
  - include: 8.3.yml tags=8.3
  - include: 9.1.yml tags=9.1
  - include: 9.2.yml tags=9.2
